
name: jmh-benchmarks

on: push

jobs:

  jmh-benchmarks:
    name: Jmh Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Clean up
        id: clean_up
        run: sbt ++2.13.8 zhttpBenchmarks/jmh:run -i 3 -wi 3 -f1 -t1 HttpCollectEval

